table Empleados
	lineageTag: 19b391ac-8b54-41b0-b550-ea3e4a5663e1

	column id
		dataType: string
		lineageTag: c56a6f41-b581-484b-a431-94b1ca94f407
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column anho_evaluacion
		dataType: int64
		formatString: 0
		lineageTag: 6bb3256d-cf82-40e4-b8d0-869febfa98c3
		summarizeBy: sum
		sourceColumn: anho_evaluacion

		annotation SummarizationSetBy = Automatic

	column area
		dataType: string
		lineageTag: f2c7d03e-c79a-4ce5-a619-216b2aad2e45
		summarizeBy: none
		sourceColumn: area

		annotation SummarizationSetBy = Automatic

	column desempenho
		dataType: int64
		lineageTag: c05cd371-ceff-4d5c-9da8-c4ae3f80d519
		summarizeBy: sum
		sourceColumn: desempenho

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column renuncia
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6a958a1c-72f0-4218-943a-3c3a83140138
		summarizeBy: none
		sourceColumn: renuncia

		annotation SummarizationSetBy = Automatic

	partition Empleados = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("10.147.19.99:5432", "PowerBI"),
				    public_ta1 = Source{[Schema="public",Item="ta1"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(public_ta1,{{"desempenho", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

