// Welcome to DAX query view! Learn more about DAX queries at https://aka.ms/dax-queries.
// Right-click on tables, columns, or measures in the data pane to access quick queries, or ask Copilot for help writing DAX.

// Select "Run" to try this sample DAX query.
FiveMinuteInterval = 
VAR Time = [duration_time_minutes]
RETURN
DATETIME(
    YEAR(Time),
    MONTH(Time),
    DAY(Time),
    HOUR(Time),
    FLOOR(MINUTE(Time), 5),
    0
)