table Casts
	lineageTag: 42d96707-5fc2-4f2b-9b7e-7e21d8bc1501

	column show_id
		dataType: string
		isHidden
		lineageTag: 7f9f2979-076a-40c0-beac-1862ba5d1b98
		summarizeBy: none
		sourceColumn: show_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column cast
		dataType: string
		lineageTag: 298d9f62-bc64-4b32-874e-cc3e5b711ab7
		summarizeBy: none
		sourceColumn: cast

		annotation SummarizationSetBy = Automatic

	partition Casts = m
		mode: import
		queryGroup: Relations
		source =
				let
				    Source = PostgreSQL.Database("10.147.19.99:5432", "PowerBI"),
				    public_ta2 = Source{[Schema="public",Item="ta2"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(public_ta2,{"type", "title", "director", "country", "date_added", "release_year", "rating", "duration", "listed_in", "description", "duration_time", "mayor_min"}),
				    #"Split Column by Delimiter" = Table.ExpandListColumn(Table.TransformColumns(#"Removed Columns", {{"cast", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "cast"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"cast", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

