table Categories
	lineageTag: d062a1ef-b126-4e2f-ae4e-33d6fa93d40c

	column show_id
		dataType: string
		lineageTag: 6f54a7ec-2748-402b-8c57-5f76578883e3
		summarizeBy: none
		sourceColumn: show_id

		annotation SummarizationSetBy = Automatic

	column listed_in
		dataType: string
		lineageTag: 69d7d5d9-b15e-4434-9b2b-1cf579ad3a98
		summarizeBy: none
		sourceColumn: listed_in

		annotation SummarizationSetBy = Automatic

	partition Categories = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("10.147.19.99:5432", "PowerBI"),
				    public_ta2 = Source{[Schema="public",Item="ta2"]}[Data],
				    #"Split Column by Delimiter" = Table.ExpandListColumn(Table.TransformColumns(public_ta2, {{"cast", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "cast"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"cast", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"cast"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns", {"show_id"}),
				    #"Split Column by Delimiter1" = Table.ExpandListColumn(Table.TransformColumns(#"Removed Duplicates", {{"director", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "director"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter1",{{"director", type text}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type1",{"director"}),
				    #"Removed Duplicates1" = Table.Distinct(#"Removed Columns1", {"country"}),
				    #"Split Column by Delimiter2" = Table.ExpandListColumn(Table.TransformColumns(#"Removed Duplicates1", {{"country", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "country"),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Delimiter2",{{"country", type text}}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Changed Type2",{"country"}),
				    #"Removed Duplicates2" = Table.Distinct(#"Removed Columns2", {"date_added"}),
				    #"Split Column by Delimiter3" = Table.ExpandListColumn(Table.TransformColumns(#"Removed Duplicates2", {{"listed_in", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "listed_in"),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Split Column by Delimiter3",{{"listed_in", type text}}),
				    #"Removed Columns3" = Table.RemoveColumns(#"Changed Type3",{"type", "title", "date_added", "release_year", "rating", "duration", "description", "duration_time", "mayor_min"})
				in
				    #"Removed Columns3"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

