table Categories
	lineageTag: 132b6959-e588-41fd-9659-c0cac0d97be8

	column show_id
		dataType: string
		isHidden
		lineageTag: bc0d7731-e77a-4641-93e0-c5dc58b058d9
		summarizeBy: none
		sourceColumn: show_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Categories
		dataType: string
		lineageTag: 63fd6a3f-2774-41e8-9558-3f5ffa21cf77
		summarizeBy: none
		sourceColumn: Categories

		annotation SummarizationSetBy = Automatic

	partition Categories = m
		mode: import
		queryGroup: Relations
		source =
				let
				    Source = PostgreSQL.Database("10.147.19.99:5432", "PowerBI"),
				    public_ta2 = Source{[Schema="public",Item="ta2"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(public_ta2,{"cast", "country", "type", "title", "director", "date_added", "release_year", "rating", "duration", "description", "duration_time", "mayor_min"}),
				    #"Split Column by Delimiter" = Table.ExpandListColumn(Table.TransformColumns(#"Removed Columns", {{"listed_in", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "listed_in"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"listed_in", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"listed_in", "Categories"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

