table Countries
	lineageTag: 728cef5d-b7ce-4e68-9524-86b99551f9e8

	column show_id
		dataType: string
		isHidden
		lineageTag: ddf4947f-b6a2-40d0-94cc-03c760dd99cb
		summarizeBy: none
		sourceColumn: show_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 6e783e83-8c7d-4d4d-a8c9-197e19c2673c
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	partition Countries = m
		mode: import
		queryGroup: Relations
		source =
				let
				    Source = PostgreSQL.Database("10.147.19.99:5432", "PowerBI"),
				    public_ta2 = Source{[Schema="public",Item="ta2"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(public_ta2,{"cast", "type", "title", "director", "date_added", "release_year", "rating", "duration", "listed_in", "description", "duration_time", "mayor_min"}),
				    #"Split Column by Delimiter" = Table.ExpandListColumn(Table.TransformColumns(#"Removed Columns", {{"country", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "country"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"country", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

