table Countries
	lineageTag: 50046632-610c-449b-94ab-c23451266009

	column show_id
		dataType: string
		lineageTag: 04a95b26-5779-4209-b4e3-15afd0d0b190
		summarizeBy: none
		sourceColumn: show_id

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 789781ce-e5d9-4b38-8ba3-0901babca1f8
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	partition Countries = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("10.147.19.99:5432", "PowerBI"),
				    public_ta2 = Source{[Schema="public",Item="ta2"]}[Data],
				    #"Split Column by Delimiter" = Table.ExpandListColumn(Table.TransformColumns(public_ta2, {{"cast", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "cast"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"cast", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"cast"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns", {"show_id"}),
				    #"Split Column by Delimiter1" = Table.ExpandListColumn(Table.TransformColumns(#"Removed Duplicates", {{"director", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "director"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter1",{{"director", type text}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type1",{"director"}),
				    #"Removed Duplicates1" = Table.Distinct(#"Removed Columns1", {"country"}),
				    #"Split Column by Delimiter2" = Table.ExpandListColumn(Table.TransformColumns(#"Removed Duplicates1", {{"country", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "country"),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Delimiter2",{{"country", type text}}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Changed Type2",{"type", "title", "date_added", "release_year", "rating", "duration", "listed_in", "description", "duration_time", "mayor_min"})
				in
				    #"Removed Columns2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

