table Directors
	lineageTag: 6138bba2-7252-471f-a4e4-4a0024588b67

	column show_id
		dataType: string
		isHidden
		lineageTag: e9bc2bec-734a-4195-b2fa-9c3c46b2323b
		summarizeBy: none
		sourceColumn: show_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column director
		dataType: string
		lineageTag: 117b8370-5fe3-46a6-a248-a1ea378743ef
		summarizeBy: none
		sourceColumn: director

		annotation SummarizationSetBy = Automatic

	partition Directors = m
		mode: import
		queryGroup: Relations
		source =
				let
				    Source = PostgreSQL.Database("10.147.19.99:5432", "PowerBI"),
				    public_ta2 = Source{[Schema="public",Item="ta2"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(public_ta2,{"cast", "country", "type", "title", "date_added", "release_year", "rating", "duration", "listed_in", "description", "duration_time", "mayor_min"}),
				    #"Split Column by Delimiter" = Table.ExpandListColumn(Table.TransformColumns(#"Removed Columns", {{"director", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "director"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"director", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

