table DisneyMovies
	lineageTag: 95b6dc6d-6135-4508-b510-7b9c752dbd0c

	column show_id
		dataType: string
		lineageTag: ab0e1732-5bd9-4060-9a6d-6c295901779b
		summarizeBy: none
		sourceColumn: show_id

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: fb3c388d-24b1-4d49-86c9-d23e6f15276a
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column title
		dataType: string
		lineageTag: 398972d4-4354-4a8d-914c-ce8683459136
		summarizeBy: none
		sourceColumn: title

		annotation SummarizationSetBy = Automatic

	column date_added
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6011447a-9b54-4b3c-b962-45dc86ea9248
		summarizeBy: none
		sourceColumn: date_added

		variation Variation
			isDefault
			relationship: 66dd4ecd-07ee-441b-a4e5-6713cd005ca4
			defaultHierarchy: LocalDateTable_d80d3102-cc7b-48a4-b336-3f8e69c555b9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column release_year
		dataType: int64
		formatString: 0
		lineageTag: 8632c4b8-968b-48c7-b0f4-6d4ac0e0af7a
		summarizeBy: sum
		sourceColumn: release_year

		annotation SummarizationSetBy = Automatic

	column rating
		dataType: string
		lineageTag: e31ddd3b-6539-4de1-8bc1-c4541c2a5b2d
		summarizeBy: none
		sourceColumn: rating

		annotation SummarizationSetBy = Automatic

	column duration
		dataType: string
		lineageTag: 34b75058-1fb2-4035-a850-e234ce85ebaa
		summarizeBy: none
		sourceColumn: duration

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 82daa787-dfa3-4ae3-b548-2d130cac64f1
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column duration_time
		dataType: int64
		formatString: 0
		lineageTag: 02609d9f-fef3-49b0-b5d6-679d5e7727bd
		summarizeBy: sum
		sourceColumn: duration_time

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"DisneyMovies","TableItemName":"duration_time (bins)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column mayor_min
		dataType: string
		lineageTag: 1c45fa01-9895-47ff-814a-29c0571a369a
		summarizeBy: none
		sourceColumn: mayor_min

		annotation SummarizationSetBy = Automatic

	column 'duration_time (bins)' =
			IF(
				ISBLANK('DisneyMovies'[duration_time]),
				BLANK(),
				INT('DisneyMovies'[duration_time] / 30) * 30
			)
		formatString: 0
		lineageTag: 2356c6b8-115d-4371-ab58-26cc56b82dff
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "DisneyMovies"
				          }
				        },
				        "Property": "duration_time"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 30.0,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"d","Entity":"DisneyMovies"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"duration_time"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"duration_time"}},"Size":30.0}}}}

		annotation SummarizationSetBy = Automatic

	partition DisneyMovies = m
		mode: import
		queryGroup: Data
		source =
				let
				    Source = PostgreSQL.Database("10.147.19.99:5432", "PowerBI"),
				    public_ta2 = Source{[Schema="public",Item="ta2"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(public_ta2,{"cast", "country", "listed_in", "director"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

